(() => {
  const nomes=["ÁRIES","TOURO","GÊMEOS","CÂNCER","LEÃO","VIRGEM","LIBRA","ESCORPIÃO","SAGITÁRIO","CAPRICÓRNIO","AQUÁRIO","PEIXES"];
  const slugPorNome={"ÁRIES":"aries","TOURO":"touro","GÊMEOS":"gemeos","CÂNCER":"cancer","LEÃO":"leao","VIRGEM":"virgem","LIBRA":"libra","ESCORPIÃO":"escorpiao","SAGITÁRIO":"sagitario","CAPRICÓRNIO":"capricornio","AQUÁRIO":"aquario","PEIXES":"peixes"};
  const elementoPorSigno={aries:"Fogo",leao:"Fogo",sagitario:"Fogo",touro:"Terra",virgem:"Terra",capricornio:"Terra",gemeos:"Ar",libra:"Ar",aquario:"Ar",cancer:"Água",escorpiao:"Água",peixes:"Água"};
  const API_URL="https://horoscopo-sincero.edsonfernandesvet.workers.dev/gerar-horoscopo";let signoSelecionado=null;
  function normalizar(t){return String(t||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/\s+/g," ").trim()}
  function porNome(nome){const n=normalizar(nome),encontrado=nomes.find(x=>normalizar(x)===n);if(!encontrado)return null;const slug=slugPorNome[encontrado];return{slug,nome:encontrado,elemento:elementoPorSigno[slug]}}
  function identificarElemento(el){if(!el)return null;for(const valor of[el.dataset?.signo,el.dataset?.sign,el.dataset?.value,el.getAttribute?.("aria-label")].filter(Boolean)){const d=porNome(valor);if(d)return d}return null}
  function identificarBotao(b){const d=identificarElemento(b);if(d)return d;const grid=document.getElementById("zodiacGrid");if(!grid||!b)return null;const bs=[...grid.querySelectorAll("button")],i=bs.indexOf(b);if(i>=0&&i<nomes.length)return porNome(nomes[i]);return porNome(b.textContent)}
  function marcarBotoes(){const grid=document.getElementById("zodiacGrid");if(!grid)return;[...grid.querySelectorAll("button")].forEach((b,i)=>{const d=porNome(nomes[i]);if(d){b.dataset.signo=d.nome;b.dataset.sign=d.nome;b.dataset.elemento=d.elemento}})}
  function registrarSelecao(e){const grid=document.getElementById("zodiacGrid");if(!grid||!grid.contains(e.target))return;marcarBotoes();const d=identificarBotao(e.target.closest("button,[role='button']"));if(d){signoSelecionado=d;window.__signoSelecionado=d}}
  document.addEventListener("click",registrarSelecao,true);setTimeout(marcarBotoes,0);
  function descobrirSigno(){if(signoSelecionado)return signoSelecionado;if(window.__signoSelecionado)return window.__signoSelecionado;marcarBotoes();const grid=document.getElementById("zodiacGrid");if(!grid)return null;return identificarBotao(grid.querySelector(".active,.selected,[aria-selected='true'],[aria-pressed='true'],[data-selected='true']"))}
  function perfilDoSigno(slug){try{if(typeof signos!=="undefined"&&signos[slug]){const s=signos[slug];return{verdade:s.verdade||"",super:s.super||"",defeito:s.defeito||"",semana:s.semana||""}}}catch(_){}return{}}
  function fallbackLocal(signo){const s=typeof signos!=="undefined"?signos[signo.slug]:null;if(!s)return null;return{verdade:s.verdade||"",superpoder:s.super||"",defeito:s.defeito||"",semana:s.semana||"",diario:s.semana||"",frase:s.verdade?s.verdade.split(/[.!?]/)[0].trim():"",exposicao:s.defeito||"",conselho:s.conselho||""}}
  function escapar(t){return String(t||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
  function criarLoading(){if(document.getElementById("horoscopoLoading"))return;const s=document.createElement("style");s.textContent="#horoscopoLoading{position:fixed;inset:0;z-index:99999;background:rgba(10,5,18,.94);display:none;align-items:center;justify-content:center;padding:24px}.hl-box{width:min(430px,92vw);text-align:center;background:#1b0d28;border:1px solid rgba(245,201,106,.35);border-radius:20px;padding:30px 24px;box-shadow:0 20px 70px rgba(0,0,0,.55)}.hl-title{color:#f5c96a;font-size:21px;font-weight:700;margin-bottom:10px}.hl-text{color:#fff8ff;font-size:15px;min-height:22px}.hl-track{height:10px;background:#33203e;border-radius:99px;overflow:hidden;margin:22px 0 9px}.hl-bar{height:100%;width:0;background:linear-gradient(90deg,#e85aad,#f5c96a);border-radius:99px;transition:width .18s ease}.hl-percent{color:#cbbbd0;font-size:13px}";document.head.appendChild(s);const o=document.createElement("div");o.id="horoscopoLoading";o.innerHTML='<div class="hl-box"><div class="hl-title">🔮 MADAME VERÔNICA</div><div class="hl-text" id="hlText"></div><div class="hl-track"><div class="hl-bar" id="hlBar"></div></div><div class="hl-percent" id="hlPercent">0%</div></div>';document.body.appendChild(o)}
  let loadingTimer;
  function loadingShow(text){criarLoading();const o=document.getElementById("horoscopoLoading"),bar=document.getElementById("hlBar"),pct=document.getElementById("hlPercent");document.getElementById("hlText").textContent=text;o.style.display="flex";let p=0;clearInterval(loadingTimer);loadingTimer=setInterval(()=>{p+=Math.max(.35,(91-p)*.035);if(p>91)p=91;bar.style.width=p+"%";pct.textContent=Math.floor(p)+"%"},120)}
  function loadingHide(){const o=document.getElementById("horoscopoLoading");if(!o)return;clearInterval(loadingTimer);document.getElementById("hlBar").style.width="100%";document.getElementById("hlPercent").textContent="100%";setTimeout(()=>o.style.display="none",180)}
  window.horoscopoLoading={show:loadingShow,hide:loadingHide};
  function renderizar(resultado,signo,dados){resultado.innerHTML=`<article class="horoscope-card"><h2>🔮 HORÓSCOPO SINCERO POR MADAME VERÔNICA</h2><p><em>Porque alguém precisava te contar a verdade.</em></p><p><strong>Signo:</strong> ${escapar(signo.nome)}</p><p><strong>Elemento:</strong> ${escapar(signo.elemento)}</p><hr><h3>💀 A VERDADE QUE NINGUÉM TE CONTA:</h3><p>${escapar(dados.verdade)}</p><h3>🔥 SEU SUPERPODER:</h3><p>${escapar(dados.superpoder)}</p><h3>🚩 SEU DEFEITO FATAL:</h3><p>${escapar(dados.defeito)}</p><h3>📅 PREVISÃO SINCERA DA SEMANA:</h3><p>${escapar(dados.semana)}</p><h3>☀️ HORÓSCOPO DE HOJE:</h3><p>${escapar(dados.diario)}</p><h3>💬 CONSELHO QUE VOCÊ VAI IGNORAR:</h3><p>${escapar(dados.conselho)}</p><p class="quote"><strong>💥 MAIS UMA EXPOSIÇÃO:</strong> ${escapar(dados.exposicao)}</p><p class="quote"><strong>📌 FRASE DO DIA:</strong> ${escapar(dados.frase)}</p><button id="shareImageBtn" class="share-btn" type="button">📲 Compartilhar como imagem</button></article>`;document.getElementById("shareImageBtn")?.addEventListener("click",async()=>{const b=document.getElementById("shareImageBtn"),o=b.innerHTML;try{b.disabled=true;b.innerHTML="🖼️ Preparando imagem...";await compartilharImagem(signo.nome,signo.elemento,dados)}catch(e){if(e?.name!=="AbortError")alert("Não consegui preparar o compartilhamento agora.")}finally{b.disabled=false;b.innerHTML=o}})}
  async function criarImagemCompartilhamento(signo,elemento,dados){const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext("2d");const grad=ctx.createLinearGradient(0,0,1080,1920);grad.addColorStop(0,"#45205b");grad.addColorStop(.42,"#160b22");grad.addColorStop(1,"#100817");ctx.fillStyle=grad;ctx.fillRect(0,0,1080,1920);ctx.textAlign="center";ctx.fillStyle="#f5c96a";ctx.font="700 30px Arial";ctx.fillText("MADAME VERÔNICA",540,90);ctx.fillStyle="#fff8ff";ctx.font="800 68px Arial";ctx.fillText(signo,540,175);ctx.fillStyle="#cbbbd0";ctx.font="500 27px Arial";ctx.fillText(elemento,540,225);return new Promise(resolve=>canvas.toBlob(resolve,"image/png",1))}
  async function compartilharImagem(signo,elemento,dados){const blob=await criarImagemCompartilhamento(signo,elemento,dados);if(!blob)throw new Error("Não foi possível criar a imagem.");const arquivo=new File([blob],`horoscopo-sincero-${slugPorNome[signo]||"signo"}.png`,{type:"image/png"});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[arquivo]}))){await navigator.share({title:`Horóscopo Sincero — ${signo}`,text:"Madame Verônica acabou de me expor.",files:[arquivo]});return}const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=arquivo.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function gerar(){const signo=descobrirSigno(),contexto=document.getElementById("context"),resultado=document.getElementById("result");if(!resultado)return;if(!signo){resultado.classList.remove("hidden");resultado.innerHTML='<div class="error-box">🔮 Primeiro escolha seu signo, criatura cósmica.</div>';return}const botao=document.getElementById("generateBtn"),original=botao?.innerHTML;if(botao){botao.disabled=true;botao.innerHTML="🔮 Madame está pensando..."}resultado.classList.remove("hidden");resultado.innerHTML='<div class="loading">Madame Verônica está consultando o universo. E a sua ficha criminal emocional.</div>';loadingShow("Madame Verônica está preparando sua verdade...");try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signo:signo.nome,elemento:signo.elemento,contexto:contexto?.value||"",perfil:perfilDoSigno(signo.slug)})}),text=await r.text();let dados;try{dados=JSON.parse(text)}catch{throw new Error(`Resposta inválida do servidor (HTTP ${r.status}).`)}if(!r.ok)throw new Error(dados.detail?`${dados.error||"Erro do servidor."} ${dados.detail}`:(dados.error||"Erro ao gerar horóscopo."));renderizar(resultado,signo,dados)}catch(e){const local=fallbackLocal(signo);if(local&&local.verdade&&local.superpoder&&local.defeito&&local.semana)renderizar(resultado,signo,local);else resultado.innerHTML=`<div class="error-box">Não consegui falar com Madame Verônica agora.<br><small>${escapar(e.message||"Falha de comunicação com o servidor.")}</small></div>`}finally{loadingHide();if(botao){botao.disabled=false;botao.innerHTML=original}}}
  document.addEventListener("click",e=>{const b=e.target.closest("#generateBtn");if(!b)return;e.preventDefault();e.stopImmediatePropagation();gerar()},true);
})();
