const signos = {
  aries:{nome:"ÁRIES",simbolo:"♈",elemento:"Fogo",super:"Você consegue transformar uma ida rápida ao mercado numa missão de vida. Quando todo mundo ainda está pensando, você já fez — às vezes sem ler as instruções.",defeito:"Você acha que impulsividade é personalidade forte. Amiga, nem toda discussão precisa de resposta imediata e nem toda ideia precisa virar projeto às 23h.",verdade:"Você começa 47 coisas com a confiança de quem vai dominar o mundo e termina algumas com a mesma velocidade com que responde 'depois eu vejo'. Briga, fala tudo o que pensa e cinco minutos depois já está mandando meme como se nada tivesse acontecido.",semana:"Na terça você vai querer resolver uma coisa que poderia esperar até amanhã. Não vai esperar. Na quarta alguém vai te irritar por uma coisa pequena e você vai criar uma tese de doutorado sobre o assunto. No fim da semana, uma ideia nova vai aparecer e você vai jurar que agora vai até o fim. Vamos observar.",combina:["LEÃO","porque os dois gostam de intensidade e nenhum dos dois nasceu para ficar discutindo quem manda: os dois já decidiram que são eles."],foge:["CÂNCER","porque você quer resolver tudo em cinco minutos e Câncer quer conversar sobre como se sentiu durante os últimos cinco anos."],conselho:"Antes de responder no impulso, espera dez minutos. Eu sei que isso para você parece uma eternidade, mas tenta."},
  touro:{nome:"TOURO",simbolo:"♉",elemento:"Terra",super:"Você sabe aproveitar a vida sem precisar transformar tudo numa competição. E quando decide cuidar de alguém, vira praticamente serviço de entrega emocional com comida.",defeito:"Sua teimosia já poderia ter CPF. Você percebe que está errado, fica quieto, muda de assunto e espera que o universo esqueça.",verdade:"Você chama apego de 'memória afetiva'. Aquela pessoa que saiu da sua vida há três anos ainda mora num cantinho da sua cabeça pagando aluguel atrasado. E se tiver comida envolvida, você perdoa coisas que jurou que nunca perdoaria.",semana:"Você vai adiar uma mudança porque sua rotina atual é confortável demais. Depois vai reclamar que nada muda. No meio da semana, alguém vai tentar apressar você e você vai fazer exatamente o contrário só de birra. No domingo, vai gastar dinheiro em alguma coisa que justificará como 'investimento em qualidade de vida'.",combina:["CAPRICÓRNIO","porque os dois entendem que estabilidade, comida boa e boleto pago já são praticamente uma declaração de amor."],foge:["AQUÁRIO","porque enquanto você quer saber onde vai sentar e que horas volta, Aquário ainda está tentando decidir se realmente quer ir."],conselho:"Nem toda mudança é ameaça. Às vezes você só está confortável demais para admitir que já enjoou."},
  gemeos:{nome:"GÊMEOS",simbolo:"♊",elemento:"Ar",super:"Você consegue conversar com desconhecido, motorista de aplicativo, cachorro e atendente de farmácia como se fossem amigos de infância. Informação nunca falta.",defeito:"Você tem 15 abas abertas na cabeça e nenhuma terminou de carregar. Muda de opinião, de assunto e de plano antes que os outros consigam acompanhar.",verdade:"Você tem grupo de WhatsApp para tudo e provavelmente esqueceu de responder alguém importante porque estava respondendo outra pessoa sobre uma fofoca completamente inútil. Sua curiosidade é enorme; sua capacidade de terminar o assunto original é outra história.",semana:"Uma conversa casual vai virar fofoca, que vai virar investigação, que vai virar você descobrindo uma informação que nem queria saber. Na quarta você vai prometer focar em uma coisa e, naturalmente, fará cinco. No sábado vai reencontrar alguém e falar como se tivesse visto ontem, mesmo tendo passado dois anos.",combina:["LIBRA","porque vocês conseguem transformar uma simples conversa de dez minutos em três horas sem chegar ao assunto original."],foge:["ESCORPIÃO","porque você acha que está brincando e Escorpião já abriu um dossiê sobre o que você quis dizer."],conselho:"Termina uma coisa antes de começar outra. Não precisa terminar todas hoje, mas termina pelo menos uma."},
  cancer:{nome:"CÂNCER",simbolo:"♋",elemento:"Água",super:"Você lembra de detalhes que ninguém lembra e percebe mudanças de humor antes de a pessoa abrir a boca. O problema é que às vezes percebe até o que não aconteceu.",defeito:"Você guarda mágoa com a organização de um arquivo público. Diz que está tudo bem e depois lembra exatamente do que aconteceu numa terça-feira de 2019.",verdade:"Você diz que desapegou, mas ainda sabe o aniversário da mãe do ex. Guarda foto, mensagem, presente e aquela blusa esquecida como se fosse prova de um processo judicial. E quando sente saudade, não manda mensagem: vai olhar o perfil da pessoa.",semana:"Uma lembrança antiga vai aparecer do nada e você vai passar tempo demais pensando nela. Alguém vai procurar você pedindo conselho e você vai dar um excelente conselho que deveria seguir também. No fim de semana, vai querer ficar em casa, comer alguma coisa boa e fingir que não precisa sair.",combina:["PEIXES","porque os dois conseguem sentir falta de alguém que nem está presente e ainda encontrar motivo para uma conversa de duas horas sobre isso."],foge:["ÁRIES","porque Áries quer resolver o problema agora e você ainda está explicando como se sentiu quando o problema começou."],conselho:"Nem toda lembrança precisa virar assunto atual. Guarda o carinho e solta o arquivo morto."},
  leao:{nome:"LEÃO",simbolo:"♌",elemento:"Fogo",super:"Você entra num ambiente e, mesmo quando não está tentando chamar atenção, alguém percebe. Tem presença e sabe defender quem considera seu.",defeito:"Você diz que não liga para aprovação enquanto verifica discretamente quem curtiu, quem viu e quem não comentou. Amiga, o aplicativo não mente.",verdade:"Você quer ser admirado, mas prefere fingir que simplesmente aconteceu. Quando recebe elogio, faz cara de 'imagina' por três segundos e depois lembra da frase durante seis meses. E se alguém ignorar você, aí pronto: investigação particular.",semana:"Você vai receber uma atenção que estava esperando e vai agir como se não estivesse esperando. Na quinta, uma crítica pequena vai incomodar mais do que deveria porque atingiu exatamente um ponto que você tenta esconder. No fim de semana, vai fazer algo só porque quer se sentir bem e vai ficar ótimo — mesmo que você diga que foi sem intenção.",combina:["SAGITÁRIO","porque os dois gostam de liberdade, diversão e uma plateia que saiba apreciar a história depois."],foge:["VIRGEM","porque Virgem pode apontar o detalhe que você preferia que ninguém tivesse percebido."],conselho:"Você não precisa provar seu valor toda vez que entra numa sala. Deixa algumas coisas existirem sem aplauso."},
  virgem:{nome:"VIRGEM",simbolo:"♍",elemento:"Terra",super:"Você consegue encontrar o erro que ninguém viu e ainda resolver enquanto os outros estão discutindo de quem foi a culpa.",defeito:"Você chama preocupação de planejamento. Tem uma lista para fazer a lista e provavelmente já corrigiu mentalmente este texto.",verdade:"Você fala 'não vou me estressar' enquanto reorganiza mentalmente a vida de todo mundo ao redor. Critica porque quer ajudar, ajuda porque quer controlar e controla porque, sinceramente, você acha que faria melhor.",semana:"Você vai perceber um erro que ninguém mais notou e vai ter dificuldade de deixar passar. Uma tarefa simples vai ocupar sua cabeça mais tempo do que merece. No fim da semana, você vai organizar alguma coisa que nem estava desorganizada só para recuperar a sensação de que pelo menos uma área da vida está sob controle.",combina:["TOURO","porque os dois gostam de estabilidade e ninguém vai reclamar de um jantar bom e de uma casa minimamente organizada."],foge:["LEÃO","porque você vai apontar um detalhe e Leão vai ouvir como se você tivesse declarado guerra."],conselho:"Nem todo problema precisa de solução hoje. Às vezes o mundo sobrevive perfeitamente ao seu 'depois eu arrumo'."},
  libra:{nome:"LIBRA",simbolo:"♎",elemento:"Ar",super:"Você sabe conversar sem transformar toda divergência numa guerra. Também consegue fazer qualquer ambiente parecer mais agradável sem precisar de muito esforço.",defeito:"Você demora 45 minutos para decidir o que comer e, no final, pede a mesma coisa de sempre. Sua indecisão já tem testemunhas.",verdade:"Você diz 'tanto faz' esperando que a outra pessoa escolha exatamente o que você queria. Evita conflito até quando precisa dizer não e depois reclama, em silêncio, da decisão que você mesmo deixou outra pessoa tomar.",semana:"Uma escolha pequena vai ocupar espaço demais na sua cabeça. Você vai pedir opinião para pelo menos duas pessoas e ainda ficará em dúvida. Na sexta, alguém vai pedir uma decisão simples e você vai responder 'vamos ver' com a segurança de quem sabe que não vai ver nada.",combina:["GÊMEOS","porque vocês podem conversar sobre todas as possibilidades até o restaurante fechar."],foge:["CAPRICÓRNIO","porque Capricórnio quer uma resposta objetiva enquanto você ainda está analisando os prós e contras da entrada."],conselho:"Escolhe. Uma decisão imperfeita ainda é melhor que passar a vida esperando a opção perfeita."},
  escorpiao:{nome:"ESCORPIÃO",simbolo:"♏",elemento:"Água",super:"Você percebe clima estranho antes de alguém admitir que existe clima estranho. E quando confia, leva lealdade muito a sério.",defeito:"Você diz que não está investigando, mas já viu horário online, curtida antiga e até quem segue quem. Sherlock Holmes pediria estágio.",verdade:"Você não esquece quase nada. Pode até perdoar, mas seu cérebro arquiva o acontecimento em qualidade 4K. E quando alguém diz 'não foi nada', você já sabe que foi alguma coisa.",semana:"Uma conversa vai fazer você desconfiar de algo que talvez nem seja importante. Antes de montar a teoria completa, espere a pessoa falar. Alguém do passado pode aparecer com uma mensagem e você vai analisar cada palavra como se fosse contrato. No fim da semana, vai descobrir que metade do drama estava acontecendo na sua cabeça.",combina:["CAPRICÓRNIO","porque os dois levam lealdade a sério e preferem relações que tenham conteúdo, não conversa vazia."],foge:["GÊMEOS","porque Gêmeos fala uma coisa, lembra de outra e você já está calculando se existe uma segunda intenção."],conselho:"Nem toda pessoa que não responde em dois minutos está escondendo alguma coisa. Solta o celular, criatura."},
  sagitario:{nome:"SAGITÁRIO",simbolo:"♐",elemento:"Fogo",super:"Você consegue transformar uma situação ruim em história engraçada. Tem coragem para experimentar e não costuma ficar preso ao mesmo lugar por muito tempo.",defeito:"Você confunde sinceridade com falar qualquer coisa na hora errada. E quando percebe que exagerou, tenta consertar com uma piada.",verdade:"Você fala 'bora' antes de saber para onde vai, quanto custa ou quem vai pagar. Ama liberdade, mas às vezes usa essa palavra como desculpa para não responder mensagem, compromisso ou boleto.",semana:"Você vai aceitar alguma coisa no entusiasmo e só depois perceber a logística. Uma conversa vai virar convite e o convite pode virar rolê. No domingo, você vai querer descansar justamente porque passou a semana dizendo que precisava de aventura.",combina:["ÁRIES","porque ninguém vai perguntar demais antes de fazer alguma coisa que provavelmente vai render uma história."],foge:["VIRGEM","porque Virgem quer saber horário, endereço, orçamento e plano B antes de você terminar a frase."],conselho:"Liberdade não significa fugir de toda responsabilidade. Algumas coisas precisam ser resolvidas antes do rolê."},
  capricornio:{nome:"CAPRICÓRNIO",simbolo:"♑",elemento:"Terra",super:"Você aguenta pressão e continua fazendo o que precisa ser feito. Quando decide construir alguma coisa, costuma ter mais paciência que a maioria.",defeito:"Você transforma descanso em culpa e acha que pedir ajuda é sinal de fraqueza. Depois reclama que ninguém percebe o quanto você está cansado.",verdade:"Você fala que quer tranquilidade, mas está sempre criando uma nova meta. Até quando está de férias parece que existe um projeto invisível para administrar.",semana:"Uma pendência vai consumir sua atenção porque você odeia deixar coisa pela metade. Alguém vai pedir ajuda e você provavelmente vai aceitar mesmo sem ter tempo. No fim de semana, tente não transformar descanso em reunião de planejamento.",combina:["TOURO","porque estabilidade, compromisso e uma vida minimamente organizada já contam como romance."],foge:["LIBRA","porque você quer uma decisão e Libra quer discutir todas as possibilidades antes de escolher a cor da conversa."],conselho:"Descansar não é perder produtividade. Seu corpo não é uma planilha que precisa fechar no positivo todo dia."},
  aquario:{nome:"AQUÁRIO",simbolo:"♒",elemento:"Ar",super:"Você pensa diferente e não precisa que todo mundo concorde para seguir uma ideia. Sua cabeça encontra caminhos que os outros nem estavam procurando.",defeito:"Você pode ser emocionalmente misterioso até para quem mora com você. Some para 'processar' e depois volta falando de um assunto completamente diferente.",verdade:"Você quer ser entendido, mas odeia explicar demais. Quando alguém tenta controlar sua rotina, você imediatamente sente vontade de fazer exatamente o contrário só para provar que ninguém manda em você.",semana:"Uma ideia fora do padrão vai aparecer e você vai querer testar imediatamente. Uma pessoa vai cobrar uma resposta emocional e você vai tentar resolver com lógica. No fim da semana, vai precisar lembrar que nem todo mundo acompanha suas mudanças de assunto na mesma velocidade.",combina:["GÊMEOS","porque os dois conseguem começar uma conversa sobre trabalho e terminar discutindo uma teoria absurda sobre o universo."],foge:["TOURO","porque você quer mudar tudo de lugar e Touro quer saber por que mexer no que já estava funcionando."],conselho:"Explica o que você sente antes de desaparecer. As pessoas não têm acesso ao seu manual interno."},
  peixes:{nome:"PEIXES",simbolo:"♓",elemento:"Água",super:"Você tem uma imaginação que transforma qualquer situação em história e percebe nuances que muita gente ignora.",defeito:"Você romantiza sinais mínimos. A pessoa mandou 'kkk' e você já está avaliando o potencial narrativo da relação.",verdade:"Você diz que está seguindo em frente enquanto ouve a música que lembra a pessoa e olha para o teto pensando na vida. Tem empatia até demais e, às vezes, sofre por problemas que nem são seus.",semana:"Uma lembrança vai bater forte e você vai dar significado demais para uma coincidência. Alguém vai desabafar com você e, quando perceber, estará carregando o problema da pessoa no colo. No fim de semana, faça alguma coisa concreta antes de passar três horas imaginando cenários.",combina:["CÂNCER","porque alguém precisa chorar junto com você de madrugada e ainda entender exatamente por que a música era importante."],foge:["AQUÁRIO","porque você quer conversar sobre sentimentos e Aquário pode começar uma palestra sobre lógica."],conselho:"Sentir muito não significa precisar agir sobre tudo o que sente. Respira e deixa algumas emoções passarem."}
};

const ordem=["aries","touro","gemeos","cancer","leao","virgem","libra","escorpiao","sagitario","capricornio","aquario","peixes"];
let selecionado=null;
const grid=document.getElementById("zodiacGrid");
const result=document.getElementById("result");

ordem.forEach(id=>{
  const s=signos[id];
  const b=document.createElement("button");
  b.className="sign";
  b.innerHTML='<span class="symbol">'+s.simbolo+'</span><span class="name">'+s.nome+'</span>';
  b.onclick=()=>{document.querySelectorAll(".sign").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selecionado=id;};
  grid.appendChild(b);
});

document.getElementById("generateBtn").onclick=()=>{
  if(!selecionado){
    alert("🔮 Ô, criatura sem identidade cósmica! Qual é o teu signo? Se não souber, me diz a data de nascimento que eu descubro e já te julgo de uma vez.");
    return;
  }
  const s=signos[selecionado];
  const contexto=document.getElementById("context").value.trim();
  const extra=contexto?'<p class="quote"><strong>Madame recebeu seu contexto:</strong> "'+escapeHtml(contexto)+'"<br><br>Agora presta atenção porque eu vou considerar isso na leitura. Não adianta fingir que não contou.</p>':"";
  result.innerHTML=
    '<div class="title"><h2>🔮 HORÓSCOPO SINCERO POR MADAME VERÔNICA</h2><p class="subtitle">"Porque alguém precisava te contar a verdade."</p><div class="meta">Signo: '+s.nome+' '+s.simbolo+' · Elemento: '+s.elemento+' · Nível de Sinceridade: Brutal</div></div>'+
    '<h3>💀 A VERDADE QUE NINGUÉM TE CONTA:</h3><p>'+s.verdade+'</p>'+
    '<h3>🔥 SEU SUPERPODER (Sim, você tem um):</h3><p>'+s.super+'</p>'+
    '<h3>🚩 SEU DEFEITO FATAL (Todo mundo já percebeu, menos você):</h3><p>'+s.defeito+'</p>'+
    '<h3>📅 PREVISÃO SINCERA DA SEMANA:</h3><p>'+s.semana+'</p>'+extra+
    '<h3>💬 CONSELHO QUE VOCÊ VAI IGNORAR (Mas eu vou dar mesmo assim):</h3><p>'+s.conselho+'</p>'+
    '<h3>🎯 COMPATIBILIDADE SEM MENTIRA:</h3><div class="compat"><div><strong>Combina com: '+s.combina[0]+'</strong>'+s.combina[1]+'</div><div><strong>Foge de: '+s.foge[0]+'</strong>'+s.foge[1]+'</div></div>'+
    '';
  result.classList.remove("hidden");
  result.scrollIntoView({behavior:"smooth",block:"start"});
};

function escapeHtml(text){
  return text.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
}